service: url-shortening-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: migrations

functions:
  createUrl:
    handler: create.createUrl
    events:
      - http:
          path: create
          method: post
          cors: true

  getUrl:
    handler: get.getUrl
    events:
      - http:
          path: get
          method: get
          cors: true
